name: absensi_online
version: 1.0.0+1
publish_to: none
description: aplikasi absensi online dengan geolocation
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: 2.20.0
  firebase_auth: 4.12.0
  cloud_firestore: 4.12.1
  firebase_storage: 11.4.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

