// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-U-NCTcg2Xb8ruUkdQ_3LInVnog-q1EY',
    appId: '1:553956103851:web:54239e55af6952b64309ee',
    messagingSenderId: '553956103851',
    projectId: 'abensi-67190',
    authDomain: 'abensi-67190.firebaseapp.com',
    storageBucket: 'abensi-67190.appspot.com',
    measurementId: 'G-LCMWCXDMVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOn1jcEfXcjDb0F6foHHIFlEaryvGY3Sw',
    appId: '1:553956103851:android:bfe6f543c451de9c4309ee',
    messagingSenderId: '553956103851',
    projectId: 'abensi-67190',
    storageBucket: 'abensi-67190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8wKIkNixyL5WUI4H3SOMhHOfW4254tiE',
    appId: '1:553956103851:ios:3e379aa6d72658dc4309ee',
    messagingSenderId: '553956103851',
    projectId: 'abensi-67190',
    storageBucket: 'abensi-67190.appspot.com',
    iosBundleId: 'com.jaarzx.geoabsensi.absensiOnline',
  );
}
